# -*- coding: utf-8 -*-
"""CLASE 1: ESTRUCTURAS DE SELECCION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlvNKlp1fhRc97zO7CoOG5kJ9FoM9fhw

#Estructuras de seleccion
Evaluan una condicion de verdad.

1. IF/ELSE
2. IF TERNARIO
3. CASE
4. IF/ELIF(ELSE

##1. IF/ELSE
Sólo tiene dos posibles respuestas (V) o (F). Sintaxis


```
if (condicion):
  aquí se ejecuta código **si** la condicion es verdadera.
else:
  aquí se ejecuta el código **si** la condicion es falsa.
```
"""

lluvia=input("Está lloviendo?")

if lluvia=="no":
  print("Te recomiendo ir al parque.cierra las ventanas")
else:
  if lluvia=="un poquito": # 2 iguales(==) es una comparación; 1 igual(=) es asignar
    print("Te sugiero que si vas al parque lleva sombrilla.")
  else:
    if lluvia=="sí":
      print("Cierra las ventanas")
    else:
      print("resguardese")